### PR TITLE
[Port to foxy] Add support for namespace

### PR DESCRIPTION
**Pull request by homalozoa**
Signed-off-by: Homalozoa <xuhaiwang@xiaomi.com>

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @paeunt 

`foxy-devel` branch, currently, is only used to create the packages. As the master currently is for Foxy, I usually sync `master` with `foxy-devel` before creating the packages. 

So, I would close this PR, and would work in #3 .

Thanks!!

**Comment by homalozoa** [comment]
Hi. But the newest version is galactic, perhaps master branch should be port to galactic, and leave foxy-devel for foxy version. What do you think so?

**Comment by fmrico** [comment]
Hi @paeunt 

> Hi. But the newest version is galactic, perhaps the master branch should be port to galactic, and leave foxy-devel for foxy version. What do you think so?

Yes, you are right. As soon as `master` starts to point to Galactic (probably soon), `foxy-devel` will contain the development for Foxy (only bug fixes).

Meanwhile, only PRs to `master` would count.

**Comment by fmrico** [comment]
I am closing this now that #3 has been merged

**Pull request closed without merging**
